(* Version 8.18 *)

From Coq Require Export
  FSets.FSetCompat
  FSets.FSetCompat
  FSets.FMapPositive
  FSets.FMapWeakList
  FSets.FMapFacts
  FSets.FSetProperties
  FSets.FMapList
  FSets.FMapAVL
  FSets.FSetEqProperties
  FSets.FSetList
  FSets.FSetDecide
  FSets.FSetBridge
  FSets.FMapFullAVL
  FSets.FMaps
  FSets.FSetAVL
  FSets.FMapInterface
  FSets.FSetPositive
  FSets.FSetFacts
  FSets.FSetWeakList
  FSets.FSetInterface
  FSets.FSets
  FSets.FSetToFiniteSet
  Init.Datatypes
  Init.Tauto
  Init.Logic
  Init.Peano
  Init.Number
  Init.Prelude
  Init.Ltac
  Init.Specif
  Init.Byte
  Init.Tactics
  Init.Hexadecimal
  Init.Nat
  Init.Wf
  Init.Notations
  Init.Decimal
  ssrmatching.ssrmatching
  Strings.Ascii
  Strings.String
  Strings.HexString
  Strings.Byte
  Strings.BinaryString
  Strings.ByteVector
  Strings.OctalString
  Compat.AdmitAxiom
  Compat.Coq817
  Compat.Coq818
  Compat.Coq816
  setoid_ring.BinList
  setoid_ring.Cring
  setoid_ring.Ncring_initial
  setoid_ring.Rings_Q
  setoid_ring.NArithRing
  setoid_ring.ArithRing
  setoid_ring.Ring_tac
  setoid_ring.Ring_polynom
  setoid_ring.Algebra_syntax
  setoid_ring.Ring_theory
  setoid_ring.Rings_R
  setoid_ring.Ncring
  setoid_ring.ZArithRing
  setoid_ring.Ncring_tac
  setoid_ring.Ncring_polynom
  setoid_ring.Ring_base
  setoid_ring.Ring
  setoid_ring.Field_theory
  setoid_ring.InitialRing
  setoid_ring.Field_tac
  setoid_ring.Rings_Z
  setoid_ring.Field
  setoid_ring.RealField
  setoid_ring.Integral_domain
  Numbers.Cyclic.Abstract.DoubleType
  Numbers.Cyclic.Abstract.CyclicAxioms
  Numbers.Cyclic.Abstract.NZCyclic
  Numbers.Cyclic.Abstract.CarryType
  Numbers.Cyclic.ZModulo.ZModulo
  Numbers.Cyclic.Int31.Int31
  Numbers.Cyclic.Int31.Ring31
  Numbers.Cyclic.Int31.Cyclic31
  Numbers.Cyclic.Int63.Cyclic63
  Numbers.Cyclic.Int63.Uint63
  Numbers.Cyclic.Int63.PrimInt63
  Numbers.Cyclic.Int63.Sint63
  Numbers.Cyclic.Int63.Ring63
  Numbers.DecimalString
  Numbers.HexadecimalR
  Numbers.HexadecimalFacts
  Numbers.NumPrelude
  Numbers.HexadecimalN
  Numbers.AltBinNotations
  Numbers.Natural.Abstract.NGcd
  Numbers.Natural.Abstract.NLog
  Numbers.Natural.Abstract.NParity
  Numbers.Natural.Abstract.NMulOrder
  Numbers.Natural.Abstract.NDefOps
  Numbers.Natural.Abstract.NAxioms
  Numbers.Natural.Abstract.NDiv0
  Numbers.Natural.Abstract.NMaxMin
  Numbers.Natural.Abstract.NBase
  Numbers.Natural.Abstract.NOrder
  Numbers.Natural.Abstract.NBits
  Numbers.Natural.Abstract.NPow
  Numbers.Natural.Abstract.NProperties
  Numbers.Natural.Abstract.NDiv
  Numbers.Natural.Abstract.NLcm0
  Numbers.Natural.Abstract.NStrongRec
  Numbers.Natural.Abstract.NSqrt
  Numbers.Natural.Abstract.NLcm
  Numbers.Natural.Abstract.NIso
  Numbers.Natural.Abstract.NAddOrder
  Numbers.Natural.Abstract.NAdd
  Numbers.Natural.Abstract.NSub
  Numbers.Natural.Peano.NPeano
  Numbers.Natural.Binary.NBinary
  Numbers.DecimalPos
  Numbers.DecimalQ
  Numbers.DecimalFacts
  Numbers.DecimalN
  Numbers.HexadecimalNat
  Numbers.HexadecimalString
  Numbers.HexadecimalQ
  Numbers.DecimalR
  Numbers.NatInt.NZLog
  Numbers.NatInt.NZOrder
  Numbers.NatInt.NZGcd
  Numbers.NatInt.NZMul
  Numbers.NatInt.NZDiv
  Numbers.NatInt.NZAxioms
  Numbers.NatInt.NZPow
  Numbers.NatInt.NZSqrt
  Numbers.NatInt.NZParity
  Numbers.NatInt.NZMulOrder
  Numbers.NatInt.NZAddOrder
  Numbers.NatInt.NZBase
  Numbers.NatInt.NZBits
  Numbers.NatInt.NZProperties
  Numbers.NatInt.NZDomain
  Numbers.NatInt.NZAdd
  Numbers.HexadecimalPos
  Numbers.BinNums
  Numbers.HexadecimalZ
  Numbers.Integer.Abstract.ZAxioms
  Numbers.Integer.Abstract.ZLt
  Numbers.Integer.Abstract.ZParity
  Numbers.Integer.Abstract.ZGcd
  Numbers.Integer.Abstract.ZMul
  Numbers.Integer.Abstract.ZMulOrder
  Numbers.Integer.Abstract.ZDivEucl
  Numbers.Integer.Abstract.ZPow
  Numbers.Integer.Abstract.ZMaxMin
  Numbers.Integer.Abstract.ZAddOrder
  Numbers.Integer.Abstract.ZSgnAbs
  Numbers.Integer.Abstract.ZLcm
  Numbers.Integer.Abstract.ZDivFloor
  Numbers.Integer.Abstract.ZProperties
  Numbers.Integer.Abstract.ZBase
  Numbers.Integer.Abstract.ZBits
  Numbers.Integer.Abstract.ZAdd
  Numbers.Integer.Abstract.ZDivTrunc
  Numbers.Integer.NatPairs.ZNatPairs
  Numbers.Integer.Binary.ZBinary
  Numbers.DecimalNat
  Numbers.NaryFunctions
  Numbers.DecimalZ
  Setoids.Setoid
  Structures.OrdersTac
  Structures.DecidableType
  Structures.OrderedType
  Structures.EqualitiesFacts
  Structures.OrdersAlt
  Structures.Orders
  Structures.OrderedTypeEx
  Structures.OrderedTypeAlt
  Structures.GenericMinMax
  Structures.OrdersLists
  Structures.Equalities
  Structures.OrdersFacts
  Structures.DecidableTypeEx
  Structures.OrdersEx
  Unicode.Utf8_core
  Unicode.Utf8
  Relations.Operators_Properties
  Relations.Relation_Definitions
  Relations.Relation_Operators
  Relations.Relations
  Lists.List
  Lists.ListSet
  Lists.SetoidList
  Lists.StreamMemo
  Lists.Streams
  Lists.SetoidPermutation
  Lists.ListTactics
  Lists.ListDec
  Array.PArray
  Classes.Morphisms_Prop
  Classes.CRelationClasses
  Classes.CMorphisms
  Classes.Init
  Classes.SetoidClass
  Classes.EquivDec
  Classes.SetoidDec
  Classes.Morphisms
  Classes.RelationClasses
  Classes.DecidableClass
  Classes.Morphisms_Relations
  Classes.RelationPairs
  Classes.SetoidTactics
  Classes.Equivalence
  Classes.CEquivalence
  Floats.PrimFloat
  Floats.FloatClass
  Floats.FloatOps
  Floats.FloatLemmas
  Floats.SpecFloat
  Floats.Floats
  Floats.FloatAxioms
  funind.FunInd
  funind.Recdef
  Logic.Epsilon
  Logic.ProofIrrelevance
  Logic.FunctionalExtensionality
  Logic.Eqdep_dec
  Logic.EqdepFacts
  Logic.FinFun
  Logic.SetoidChoice
  Logic.Description
  Logic.WKL
  Logic.IndefiniteDescription
  Logic.Berardi
  Logic.SetIsType
  Logic.Classical_Pred_Type
  Logic.PropFacts
  Logic.RelationalChoice
  Logic.Adjointification
  Logic.PropExtensionality
  Logic.ExtensionalFunctionRepresentative
  Logic.ProofIrrelevanceFacts
  Logic.ExtensionalityFacts
  Logic.ClassicalDescription
  Logic.HLevels
  Logic.ConstructiveEpsilon
  Logic.ClassicalEpsilon
  Logic.Diaconescu
  Logic.Eqdep
  Logic.ClassicalChoice
  Logic.Hurkens
  Logic.ClassicalFacts
  Logic.Decidable
  Logic.ChoiceFacts
  Logic.Classical_Prop
  Logic.WeakFan
  Logic.Classical
  Logic.StrictProp
  Logic.ClassicalUniqueChoice
  Logic.PropExtensionalityFacts
  Logic.JMeq
  Reals.Abstract.ConstructiveSum
  Reals.Abstract.ConstructiveLimits
  Reals.Abstract.ConstructiveLUB
  Reals.Abstract.ConstructiveMinMax
  Reals.Abstract.ConstructiveAbs
  Reals.Abstract.ConstructiveRealsMorphisms
  Reals.Abstract.ConstructivePower
  Reals.Abstract.ConstructiveReals
  Reals.Cos_plus
  Reals.Ranalysis_reg
  Reals.Integration
  Reals.Rtrigo_facts
  Reals.ClassicalDedekindReals
  Reals.Rbase
  Reals.RiemannInt
  Reals.Rgeom
  Reals.Ranalysis3
  Reals.Raxioms
  Reals.Rpow_def
  Reals.Rseries
  Reals.Rlogic
  Reals.PSeries_reg
  Reals.Rregisternames
  Reals.Ranalysis4
  Reals.Rlimit
  Reals.R_sqrt
  Reals.Alembert
  Reals.Rcomplete
  Reals.Rfunctions
  Reals.RList
  Reals.DiscrR
  Reals.Rtrigo1
  Reals.Rtrigo_fun
  Reals.R_sqr
  Reals.Rtrigo_def
  Reals.Sqrt_reg
  Reals.RIneq
  Reals.PartSum
  Reals.R_Ifp
  Reals.Ratan
  Reals.Rtrigo_calc
  Reals.Cauchy_prod
  Reals.NewtonInt
  Reals.Cos_rel
  Reals.Rsqrt_def
  Reals.Rpower
  Reals.ROrderedType
  Reals.Cauchy.ConstructiveRcomplete
  Reals.Cauchy.ConstructiveCauchyRealsMult
  Reals.Cauchy.ConstructiveExtra
  Reals.Cauchy.ConstructiveCauchyAbs
  Reals.Cauchy.QExtra
  Reals.Cauchy.PosExtra
  Reals.Cauchy.ConstructiveCauchyReals
  Reals.Binomial
  Reals.Ranalysis5
  Reals.ClassicalConstructiveReals
  Reals.Ranalysis1
  Reals.Rprod
  Reals.AltSeries
  Reals.SplitRmult
  Reals.Rbasic_fun
  Reals.Rtopology
  Reals.Rtrigo_reg
  Reals.SeqSeries
  Reals.Ranalysis
  Reals.Runcountable
  Reals.Reals
  Reals.SeqProp
  Reals.SplitAbsolu
  Reals.Rminmax
  Reals.Rdefinitions
  Reals.Rsigma
  Reals.MVT
  Reals.Rtrigo_alt
  Reals.Ranalysis2
  Reals.ArithProp
  Reals.Rderiv
  Reals.Rtrigo
  Reals.RiemannInt_SF
  Reals.Exp_prop
  Reals.Machin
  micromega.ZifyN
  micromega.ZifyClasses
  micromega.OrderedRing
  micromega.Zify
  micromega.RMicromega
  micromega.Refl
  micromega.Psatz
  micromega.RingMicromega
  micromega.Tauto
  micromega.Fourier
  micromega.ZMicromega
  micromega.MExtraction
  micromega.ZCoeff
  micromega.Lqa
  micromega.Lia
  micromega.Fourier_util
  micromega.ZifyNat
  micromega.ZifyBool
  micromega.Ztac
  micromega.ZifyComparison
  micromega.Env
  micromega.EnvRing
  micromega.ZifyPow
  micromega.ZArith_hints
  micromega.Lra
  micromega.ZifyUint63
  micromega.ZifyInst
  micromega.VarMap
  micromega.DeclConstant
  micromega.QMicromega
  micromega.ZifySint63
  Vectors.VectorEq
  Vectors.VectorDef
  Vectors.Vector
  Vectors.Fin
  Vectors.VectorSpec
  rtauto.Rtauto
  rtauto.Bintree
  Arith.Plus
  Arith.Compare
  Arith.Mult
  Arith.Gt
  Arith.Le
  Arith.PeanoNat
  Arith.Arith
  Arith.Euclid
  Arith.Max
  Arith.Peano_dec
  Arith.Minus
  Arith.Compare_dec
  Arith.Lt
  Arith.Bool_nat
  Arith.EqNat
  Arith.Min
  Arith.Between
  Arith.Factorial
  Arith.Even
  Arith.Div2
  Arith.Cantor
  Arith.Arith_base
  Arith.Arith_prebase
  Arith.Wf_nat
  ssr.ssreflect
  ssr.ssrclasses
  ssr.ssrbool
  ssr.ssrunder
  ssr.ssrfun
  ssr.ssrsetoid
  derive.Derive
  Wellfounded.Inverse_Image
  Wellfounded.Transitive_Closure
  Wellfounded.Lexicographic_Product
  Wellfounded.Union
  Wellfounded.Disjoint_Union
  Wellfounded.Inclusion
  Wellfounded.Lexicographic_Exponentiation
  Wellfounded.Well_Ordering
  Wellfounded.Wellfounded
  NArith.Ngcd_def
  NArith.BinNatDef
  NArith.NArith
  NArith.Ndec
  NArith.Ndiv_def
  NArith.Ndist
  NArith.BinNat
  NArith.Nnat
  NArith.Nsqrt_def
  NArith.Ndigits
  Sets.Relations_3_facts
  Sets.Partial_Order
  Sets.Permut
  Sets.Relations_2_facts
  Sets.Relations_1
  Sets.Finite_sets
  Sets.Multiset
  Sets.Powerset_facts
  Sets.Integers
  Sets.Relations_1_facts
  Sets.Ensembles
  Sets.Relations_2
  Sets.Powerset_Classical_facts
  Sets.Image
  Sets.Classical_sets
  Sets.Constructive_sets
  Sets.Finite_sets_facts
  Sets.Infinite_sets
  Sets.Cpo
  Sets.Powerset
  Sets.Relations_3
  Sets.Uniset
  Bool.Sumbool
  Bool.IfProp
  Bool.BoolOrder
  Bool.BoolEq
  Bool.DecBool
  Bool.Zerob
  Bool.Bool
  Bool.Bvector
  ZArith.Znumtheory
  ZArith.Zmax
  ZArith.Zcomplements
  ZArith.Zeven
  ZArith.ZArith_dec
  ZArith.ZArith_base
  ZArith.Zpow_alt
  ZArith.Zdiv
  ZArith.BinIntDef
  ZArith.Zcompare
  ZArith.Zmisc
  ZArith.Zbool
  ZArith.Zorder
  ZArith.Zeuclid
  ZArith.Zhints
  ZArith.ZArith
  ZArith.Znat
  ZArith.Zpow_def
  ZArith.Zbitwise
  ZArith.Wf_Z
  ZArith.Zpow_facts
  ZArith.Zgcd_alt
  ZArith.Zmin
  ZArith.Zwf
  ZArith.Zabs
  ZArith.BinInt
  ZArith.Int
  ZArith.Zquot
  ZArith.Zdigits
  ZArith.Zpower
  ZArith.Zminmax
  ZArith.auxiliary
  Program.Basics
  Program.Program
  Program.Tactics
  Program.Equality
  Program.Utils
  Program.Syntax
  Program.Wf
  Program.Combinators
  Program.Subset
  Sorting.Sorting
  Sorting.Heap
  Sorting.PermutEq
  Sorting.PermutSetoid
  Sorting.Sorted
  Sorting.Permutation
  Sorting.CPermutation
  Sorting.Mergesort
  omega.PreOmega
  omega.OmegaLemmas
  QArith.Qreals
  QArith.Qpower
  QArith.QOrderedType
  QArith.Qround
  QArith.Qfield
  QArith.Qring
  QArith.Qminmax
  QArith.Qabs
  QArith.Qcanon
  QArith.QArith
  QArith.Qreduction
  QArith.QArith_base
  QArith.Qcabs
  nsatz.NsatzTactic
  nsatz.Nsatz
  btauto.Algebra
  btauto.Btauto
  btauto.Reflect
  MSets.MSetProperties
  MSets.MSetInterface
  MSets.MSets
  MSets.MSetToFiniteSet
  MSets.MSetGenTree
  MSets.MSetEqProperties
  MSets.MSetList
  MSets.MSetRBT
  MSets.MSetFacts
  MSets.MSetDecide
  MSets.MSetAVL
  MSets.MSetPositive
  MSets.MSetWeakList
  extraction.ExtrOcamlZInt
  extraction.ExtrHaskellNatInt
  extraction.ExtrOCamlPArray
  extraction.ExtrHaskellZNum
  extraction.ExtrHaskellZInt
  extraction.ExtrOcamlBasic
  extraction.ExtrHaskellNatNum
  extraction.ExtrHaskellZInteger
  extraction.ExtrOcamlIntConv
  extraction.ExtrHaskellBasic
  extraction.Extraction
  extraction.ExtrOcamlString
  extraction.ExtrOcamlNatBigInt
  extraction.ExtrOCamlFloats
  extraction.ExtrHaskellNatInteger
  extraction.ExtrOcamlNativeString
  extraction.ExtrHaskellString
  extraction.ExtrOCamlInt63
  extraction.ExtrOcamlNatInt
  extraction.ExtrOcamlZBigInt
  extraction.ExtrOcamlChar
  PArith.PArith
  PArith.POrderedType
  PArith.BinPos
  PArith.Pnat
  PArith.BinPosDef.
